# Generated by Django 4.2 on 2023-08-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='admins',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='admins',
            new_name='admin',
        ),
    ]
