# Generated by Django 4.2 on 2023-08-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_admins_community_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='communitu_profile/'),
        ),
        migrations.AddField(
            model_name='group',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='groups_profile/'),
        ),
    ]
