# Generated by Django 4.2 on 2023-08-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_profile_picture_group_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('-date_created',)},
        ),
    ]
