# Generated by Django 4.2 on 2023-09-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_community_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='community_profile/'),
        ),
    ]
