# Generated by Django 4.2 on 2023-08-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
