# Generated by Django 4.2 on 2023-08-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowship',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
