# Generated by Django 4.2 on 2023-08-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userfollowship_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=20),
        ),
    ]
