# Generated by Django 4.2 on 2023-09-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Public', max_length=20),
        ),
    ]
